import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai'
import Image from "next/image"
import andyPicture from '../public/AndyProfilePicture.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Andy Huang Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40'>
        <section className='min-h-screen'>
          <nev className="py-10 mb-12 flex justify-between">
            <h1 className='text-xl font-mono font-bold'>Andy Huang</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer text-xl' /></li>
              <li className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'><a href='#'></a> Resume</li>
            </ul>
          </nev>
          <dev className="text-center p-10">
            <h2 className='text-6xl py-2 text-teal-600 font-semibold md:text-7xl lg:text-8xl'>Andy Huang</h2>
            <h3 className='text-2xl py-2 md:text-3xl lg:text-4xl'>Computer Science Student at Wayne State</h3>
            <p className='text-md py-5 leading-8 text-gray-800 mx-auto max-w-4xl md:text-lg lg:text-xl'>
              I'm a CS student in my third year of undergraduate studies, with experience in various programming languages and tools.
              I'm currently looking for an internship/job to gain some experience in said field.
            </p>
          </dev>
          <dev className="text-5xl flex justify-center gap-16 py-3 text-gray-500">
            <a href='https://www.linkedin.com/in/andy-huang-649046212/' className='hover:text-teal-500'><AiFillLinkedin /></a>
            <a href='https://github.com/AndyHCode' className='hover:text-teal-500'><AiFillGithub /></a>
          </dev>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-96 md:h-96">
            <Image src={andyPicture}/>
          </div>
        </section>
        <section>
          <div>
            <div className='shadow-lg rounded-lg p-5'>
            <h3 className='text-3xl py-1 mt-5 text-center md:text-4xl lg:text-5xl'>About Me</h3>
            <p className='text-md py-8 leading-2 text-gray-80 text-center max-w-4xl mx-auto md:text-lg lg:text-xl'>
             I am an aspiring Computer Science student who possesses an interest 
             in both software and hardware. Over the years, I have gained extensive 
             experience constructing computer towers for acquaintances and relatives, as 
             well as providing assistance in resolving their software-related issues. 
             Additionally, I have amassed four years of expertise in creating 3D CAD models 
             and 2D orthographic drawings for 3D printing or any endeavors. 
            </p>
            </div>
            <div className='shadow-lg rounded-lg p-5'>
            <h3 className='text-3xl py-1 mt-5 text-center md:text-4xl lg:text-5xl'>What im currently learning</h3>
            <p className='text-md py-8 leading-2 text-gray-80 text-center max-w-4xl mx-auto md:text-lg lg:text-xl'>
              Currently im learning about the basic of frontend development with some framework. 
              So mainly focusing on html, css, javascript, react, and tailwind. For example this 
              Portfolio is written using mainly react and tailwind! I'm also have some interest in machine
              learning so I have been messing around with stable diffusion (AUTOMATIC111 version).
            </p>
            </div>
          </div>
          <div className=''>
            <div className='text-center shadow-lg pg-10 rounded-xl my-10 max-w-md mx-auto pb-3'>
              <div className='flex justify-center'><Image src={code} width={100} height={100} /></div>
              <h3 className='text-lg font-bold pt-8 pb-2'>Languages/Tools</h3>
              <p className='text-gray-800 py-2'><spam className='text-teal-600'>Programming language:</spam> C/C++, Python, Java</p>
              <p className='text-gray-800 py-2'><spam className='text-teal-600'>TextEditor:</spam> VsCode/Vim</p>
              <p className='text-gray-800 py-2'><spam className='text-teal-600'>OS:</spam> Windows/Linux</p>
            </div>

            <div className='text-center shadow-lg pg-10 rounded-xl my-10 mx-auto max-w-md pb-3'>
              <div className='flex justify-center'><Image src={design} width={100} height={100} /></div>
              <h3 className='text-lg font-bold pt-8 pb-2'>Project 1</h3>
              <p className='py-2'>Creating elegant design suited for your design theory</p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>PhotoShop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
          </div>

            <div className='text-center shadow-lg pg-10 rounded-xl my-10 pb-3 mx-auto max-w-md' >
              <div className='flex justify-center'><Image src={consulting} width={100} height={100} /></div>
              <h3 className='text-lg font-bold pt-8 pb-2'>Project</h3>
              <p className='py-2'>Creating elegant design suited for your design theory</p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>PhotoShop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
              <a href='https://github.com/AndyHCode/To-Do-Tracker'>
              <button class="bg-teal-500 hover:bg-teal-400 text-white font-bold py-2 px-4 border-b-4 border-teal-700 hover:border-teal-500 rounded">
                Open on Github
              </button></a>
            </div>

            </div>

        </section>
      </main>
    </div>
  )
}
